begin
  a
rescue Exception, CustomException => ex
  b
end
